version: '3.9'
services:
  web:
    build: .
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: mysql://fastapi_user:fastapi_password@db/fastapi_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
